<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user_login_authenticate'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<?php if ($this->messages) : ?>
    <div class="alert alert-error">
        <strong>Authentication Error!</strong>
        <br />
        <?php foreach($this->messages as $message) : ?>
            <?=$message?><br />
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<dl class="zend_form">
    <dd><?php echo $this->formInput($form->get('identity')) ?></dd>
    <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

    <?php if ($this->redirect): ?>
        <dd>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        </dd>
    <?php endif ?>

    <dd>
        <input class="submit btn-warning btn btn-large" type="submit" value="Login">
    </dd>
</dl>
<?php echo $this->form()->closeTag() ?>
<p class="text-right"><a href="<?=$this->url('user_recover_password')?>">Forgotten Password?</a></p>
