<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user_recover_password'));
$form->setAttribute('method', 'post');
?>

<?php if ($success) : ?>
        <div class="alert alert-success">
            <?=$success?><br />
        </div>
<?php else : ?>
    <?php echo $this->form()->openTag($form) ?>

    <?php if ($notification) : ?>
        <div class="alert alert-error">
            <?=$notification?><br />
        </div>
    <?php endif; ?>

    <dl class="zend_form">
        <dd><?php echo $this->formInput($form->get('email')) ?></dd>

        <dd>
            <input class="submit btn-warning btn btn-large" type="submit" value="Recover!">
        </dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
<?php endif; ?>
<p class="text-right"><a href="<?=$this->url('user_login')?>">back</a></p>
