<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user_reset_password', array('key' => $key)));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

<?php echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-error">
        <strong>Authentication Error!</strong><br />')
    ->setMessageCloseString('</div>')
    ->render($form->get('confirmPassword')) ?>

<dl class="zend_form">
    <dd><?php echo $this->formInput($form->get('password')) ?></dd>
    <dd><?php echo $this->formInput($form->get('confirmPassword')) ?></dd>

    <dd>
        <input class="submit btn-warning btn btn-large" type="submit" value="Change Password">
    </dd>
</dl>
<?php echo $this->form()->closeTag() ?>
<p class="text-right"><a href="<?=$this->url('user_login')?>">back</a></p>
